// ==========================================
var allBios = [
// ==========================================
    { category: "فخامة", name: "إمبراطور", code: "[b][c][ffd700]♚ [ffffff]EMPEROR OF FF [ffd700]♚\n[ffffff]━━━━━━━━━━━━\n[ff0000]FEARED BY ALL", premium:true },
    { category: "فخامة", name: "الملك", code: "[b][c][00FFFF]╭─◉─╮\n[ffffff]│ [ffffff]THE KING [ffffff]│\n[00FFFF]╰─◉─╯", premium:true },
    { category: "فخامة", name: "بوس", code: "[b][c][FF0000]◥███◣\n[ffffff]│▤▤│\n[ffffff]BOSS", premium:true },
    { category: "فخامة", name: "تاج الوقار", code: "[b][c][ffd700]♛ [ffffff]LEGENDARY PLAYER [ffd700]♛\n[ffffff]────────────\n[808080]SINCE 2020", premium:true },
    { category: "فخامة", name: "ملك الملوك", code: "[b][c][ffd700]⚜ [ffffff]KING OF KINGS [ffd700]⚜\n[ffffff]────────────\n[ffffff]OFFICIAL ACCOUNT", premium:true },
    { category: "فخامة", name: "أسطورة حية", code: "[b][c][00ffcc]∞ [ffffff]LIVING LEGEND [00ffcc]∞\n[ffffff]────────────\n[ffd700]ESTABLISHED" , premium:true},
    { category: "فخامة", name: "النسر الذهبي", code: "[b][c][ffd700]▶ [ffffff]GOLDEN EAGLE [ffd700]◀\n[ffffff]────────────\n[808080]FLY HIGH", premium:true },
    { category: "فخامة", name: "توثيق النخبة", code: "[b][c][00ffff]Ⓥ [ffffff] ELITE VERIFIED [00ffff]Ⓥ\n[ffffff]────────────\n[ffd700]TRUSTED", premium:true },
    { category: "فخامة", name: "بصمة فخر", code: "[b][c][ff0000]● [ffffff]LEGACY MARK [ff0000]●\n[ffffff]────────────\n[ffffff]MY STORY", premium:true },
    { category: "فخامة", name: "النجم الساطع", code: "[b][c][ffff00]★ [ffffff]SHINING STAR [ffff00]★\n[ffffff]────────────\n[00ffcc]BRILLIANT", premium:true },
    { category: "فخامة", name: "رمز الشرف", code: "[b][c][ffffff]╔══════╗\n[ffd700]║ [ffffff]HONOR CODE [ffd700]║\n[ffffff]╚══════╝", premium:true },
    { category: "فخامة", name: "صولجان القوة", code: "[b][c][ffd700]♔ [ffffff]POWER SCEPTER [ffd700]♔\n[ffffff]────────────\n[ff0000]RULER", premium:true },
    { category: "فخامة", name: "الدرع الواقي", code: "[b][c][00ffff]◈ [ffffff]IRON SHIELD [00ffff]◈\n[ffffff]────────────\n[808080]DEFENDER", premium:true },
    { category: "فخامة", name: "ملك الظلام", code: "[b][c][000000]◆ [ffd700]DARK KING [000000]◆\n[ffffff]━━━━━━━━━━━━\n[808080]SHADOW RULER", premium:true },
    { category: "فخامة", name: "المثلث الذهبي", code: "[b][c][ffd700]◣━━━━━━━━◢\n[ffffff] V I P - U S E R \n[ffd700]◤━━━━━━━━◥" },
    { category: "فخامة", name: "النجمة المشعة", code: "[b][c][00d9ff]✧ [ffffff]ELITE PLAYER[00d9ff] ✧\n[ffffff]────────────\n[00d9ff]EST. 2024" },
    { category: "فخامة", name: "هيبة ملك", code: "[b][c][ffffff]┏━━ [ffd700]♛ [ffffff] ━━┓\n   THE LEGEND   \n┗━━ [ffd700]♛ [ffffff] ━━┛" },
    { category: "فخامة", name: "التاج الذهبي", code: "[b][c][ffd700]─── { ♛ } ───\n[ffffff]OFFICIAL ACCOUNT\n[ffd700]─── 1999 ───" },
    { category: "فخامة", name: "الأسد الأسود", code: "[b][c][000000]──── ● ────\n[ffffff]STAY [00ffcc]STRONG\n[000000]──── ● ────" },
    { category: "فخامة", name: "سلطان", code: "[b][c][ffd700]♚ [ffffff]KING OF [ffd700]FREE FIRE\n[ffffff]━━━━━━━━━━━━\n[ffd700]ID: 00000000" },
    { category: "فخامة", name: "توثيق", code: "[b][c][ffff00] Ⓥ┊[00FF00] SUPERSTAR —͟͞͞★" },
    { category: "فخامة", name: "برو", code: "[B][C][00FF00]ㅤ|×͜×|ㅤ\n\\/█\\/ [00ffff]Pro" },
    { category: "فخامة", name: "ملكي", code: "[b][c][ffd700]/\\/\\/\\\n[ffffff]|[ffd700]◆◆◆[ffffff]|\n[ffd700]└─────┘" },
    { category: "فخامة", name: "فخم", code: "[ffd319][b][c] ✿ㅤ♬︎ㅤ☆ㅤ亗ㅤ〆ㅤ☃︎ ㏾ㅤ㏾ㅤ㏾ㅤ㏾ㅤ㏾ㅤ㏾" },
    { category: "فخامة", name: "برواز ملكي", code: "[b][c][ffffff]╔════════════════╗\n[ffd700]  YOUR NAME HERE  \n[ffffff]╚════════════════╝" },
    { category: "فخامة", name: "زاوية حادة", code: "[b][c][00ffcc]◤ [ffffff] اسمك هنا [00ffcc] ◢" },
    { category: "فخامة", name: "لانهاية", code: "[b][c][00ffcc] ∞ [ffffff] INFINITY [00ffcc] ∞ " },
    { category: "فخامة", name: "مستطيلات", code: "[b][c][ff0055]«« [ffffff] STERBEN [ff0055] »»" },
    { category: "فخامة", name: "شعار V", code: "[b][c][ffd700]Ⓥ [ffffff] اكتب اسمك" },
    { category: "فخامة", name: "كود ملكي", code: "[B][C][00FFFF]\n╔═══╗ \n║━◉━║\n╚═══╝\n king࿐ྂ"  },

    // === ألعاب ===
    { category: "ألعاب", name: "أسطورة السيرفر", code: "[b][c][00ffff]● [ffffff]SERVER LEGEND [00ffff]●\n[ffffff]━━━━━━━━━━━━\n[ffd700]SINCE DAY ONE", premium:true },
    { category: "ألعاب", name: "مستوى الأساطير", code: "[b][c][00ffff]Level: [ffffff]MAX\n[00ffff]Rank: [ff2d55]GRANDMASTER\n[ffffff]━━━━━━━━━━━━", premium:true },
    { category: "ألعاب", name: "رادار الهيدشوت", code: "[b][c][00ff00]● [ffffff]A I M [00ff00]●\n[ffffff]Locked on [ff0000]Head\n[00ff00]━━━━━━━━━━━━", premium:true },
    { category: "ألعاب", name: "طاقة كاملة", code: "[b][c][ffffff]HP [00ff00]██████████ 100%\n[ffffff]EP [ffff00]██████████ 100%\n[00d9ff]STATUS: GOD MODE", premium:true },
    { category: "ألعاب", name: "وضع الوحش", code: "[b][c][ff0000]⚠ BEAST MODE ⚠\n[ffffff]Win Rate: [00ff00]99.9%\n[ff0000]━━━━━━━━━━━━", premium:true },
    { category: "ألعاب", name: "قناص هيدشوت", code: "[b][c][00ffff]︻デ═一 [ffffff]SNIPER\n[00ffff]Only Headshots\n[ffffff]━━━━●━━━━", premium:true },
    { category: "ألعاب", name: "رتبة هيرويك", code: "[b][c][ff2d55]❖ HEROIC PLAYER ❖\n[ffffff]Season [ff2d55]2024\n[ffffff]────────────", premium:true },
    { category: "ألعاب", name: "كمبيوتر", code: "[b][c][ffd319] PC PLAYER\n[FF9933] 모ꄍ" },
    { category: "ألعاب", name: "قناص", code: "[b][c][00FF00] \nටᴘ┋[ffd319]\nSNIPER [FF0000]\n︻╦デ╤━╼" },
    { category: "ألعاب", name: "MVP", code: "[b][c][ffd700]★ M V P ★\n[ff0000]─[ TOP PLAYER ]─", premium:true },
    { category: "ألعاب", name: "Booyah", code: "[b][c][ffd700]B O O Y A H\n[ffffff]─────────────", premium:true },
    { category: "ألعاب", name: "هجوم", code: "[b][c][ff0000]⚔ A T T A C K ⚔\n[ffffff]── RUSH ──" },
    { category: "ألعاب", name: "دفاع", code: "[b][c][0000ff]D E F E N D\n[ffffff]──HOLD ──" },
    { category: "ألعاب", name: "قناص محترف", code: "[b][c][00ff00]S N I P E R\n[808080]▂▃▄▅▆▇█ 100%" },
    { category: "ألعاب", name: "غامر محترف", code: "[b][c][ffd700]P R O\n[00ffff]── G A M E R ──" },
    { category: "ألعاب", name: "رتبة هيرويك", code: "[b][c][ff0000]──[HEROIC]──" },
    { category: "ألعاب", name: "مستوى 100", code: "[b][ffd700]LEVEL: [ffffff] 100" },
    { category: "ألعاب", name: "إشارة رادار", code: "[b][c][00ff00]  ▂ ▃ ▄ ▅ ▆ ▇ █ [ffffff] 100%" },
    { category: "ألعاب", name: "بروفايل فخم", code: "[b][c][00ffff]━━━━●──────\n⇆ㅤㅤ◁ㅤㅤ❚❚ㅤㅤ▷ㅤㅤ↻" },
    // === مشاعر ===
    { category: "مشاعر", name: "قلب مكسور", code: "[B][C][ff0000]｡ﾟﾟ･｡･ﾟﾟ｡\n[ffffff]ﾟ･｡･°\n[ffffff]BROKEN HEART\n[ffffff]ㅤﾟ･｡･°", premium:true },
    { category: "مشاعر", name: "صمت", code: "[b][c][8888ff]Silence is [ffffff]LOUDER\n[aaaaff]than [ffffff]Words\n[8888ff]∞ ──── ● ────", premium:true },
    { category: "مشاعر", name: "أمل", code: "[b][c][ffeb3b]Keep [ffffff]Smiling\n[00e676]Life is [ffffff]Beautiful\n[ffeb3b]──────── ", premium:true },
    { category: "مشاعر", name: "وحيد", code: "[b][i][ffffff]\"أقاتل وحدي\"\n[808080]── solo player ──", premium:true },
    { category: "مشاعر", name: "صامت", code: "[b][i][808080][ S I L E N T ]\n[ffffff]── no words ──", premium:true },
    { category: "مشاعر", name: "اقتباس", code: "[b][i][ffffff]\"الصمت هو لغتي\"" },
    { category: "مشاعر", name: "قلب مكسور", code: "[b][c][ff0000]sᴀᴅ sᴛᴏʀʏ" },
    { category: "مشاعر", name: "حب", code: "[b][c][FFFFFF]ME ဗီူ╯[Ff0200]❤ [00FF00]╰ဗီူYOU" },
    { category: "مشاعر", name: "زهرة", code: "[B][C][FFD3EF]✿ Flower ✿\n[00FF00]᭄⸙ Beautiful ᭄⸙" },
    { category: "مشاعر", name: "قلب ثلاثي", code: "[b][c][ff0000]♥[ff6600]♥[ffd700]♥[00ff00]♥[00ffcc]♥[0088ff]♥[aa00ff]♥" },
    { category: "مشاعر", name: "نبض", code: "[ff0000]ﮩ٨ـﮩﮩ٨ـ♡ﮩ٨ـﮩﮩ٨ـ⁷" },

// === خطر وإثارة ===
    { category: "خطر", name: "لا يقهر", code: "[b][c][ff0000]☠ [ffffff]UNSTOPPABLE [ff0000]☠\n[ffffff]━━━━━━━━━━━━\n[ffffff]TRY ME IF YOU DARE", premium:true },
    { category: "خطر", name: "منطقة الخطر", code: "[b][c][ff0000]⚠ [ffffff]DANGER ZONE [ff0000]⚠\n[ffffff]────────────\n[ffff00]KEEP AWAY", premium:true },
    { category: "خطر", name: "جمجمة الموت", code: "[b][c][ff0000]☠ [ffffff]DEATH SKULL [ff0000]☠\n[ffffff]────────────\n[808080]NO MERCY", premium:true },
    { category: "خطر", name: "ثعبان سام", code: "[b][c][00ff00]~ [ffffff]VENOM SNAKE [00ff00]~\n[ffffff]────────────\n[ff0000]TOXIC", premium:true },
    { category: "خطر", name: "سلاح فتاك", code: "[b][c][ff0000]⚔ [ffffff]LETHAL WEAPON [ff0000]⚔\n[ffffff]────────────\n[808080]SILENT", premium:true },
    { category: "خطر", name: "عيون حمراء", code: "[b][c][ff0000]◉ [ffffff]RED EYES [ff0000]◉\n[ffffff]────────────\n[ffffff]HUNTER", premium:true },
    { category: "خطر", name: "قنبلة موقوتة", code: "[b][c][ff0000]● [ffffff]TIME BOMB [ff0000]●\n[ffffff]────────────\n[ffff00]TICKING", premium:true },
    { category: "خطر", name: "نمر أسود", code: "[b][c][808080]◆ [ffffff]BLACK PANTHER [808080]◆\n[ffffff]────────────\n[ff0000]WILD" },
    { category: "خطر", name: "صياد الليل", code: "[b][c][8888ff]◈ [ffffff]NIGHT HUNTER [8888ff]◈\n[ffffff]────────────\n[ffffff]SHADOW" },
    { category: "خطر", name: "غضب مدمر", code: "[b][c][ff7b00] [ffffff]ANGRY FIRE [ff7b00]\n[ffffff]────────────\n[ff0000]DESTROY" },
    { category: "خطر", name: "عقرب قاتل", code: "[b][c][ff0000]⦿ [ffffff]KILLER SCORPION [ff0000]⦿\n[ffffff]────────────\n[ffff00]STING" },
    { category: "خطر", name: "أوتشيها", code: "[b][c][ff0000] SHARINGAN ️\n[ffffff]Copying Your Skills...\n[ff0000]● ─── ● ─── ●" },
    { category: "خطر", name: "تحذير أمني", code: "[b][c][ff2d55]⚠ DANGER ZONE ⚠\n[ffffff]Do Not Enter\n[ff2d55]Stay Away" },
    { category: "خطر", name: "نظام مشفر", code: "[b][c][ff0000]SYSTEM ERROR...\n[ffffff]Loading [ff0000]99%\n[ffffff]ACCESS DENIED" },
    { category: "خطر", name: "جمجمة النيون", code: "[b][c][ff2d55]☠ [ffffff] NO MERCY [ff2d55] ☠\n[ffffff]────────────\n[ff2d55]Don't Follow Me" },
    { category: "خطر", name: "انتقام", code: "[b][c][ff0000]R E V E N G E\n[ffffff]─────────────" },
    { category: "خطر", name: "مقبرة", code: "[b][c][808080]  †\n[ffffff]━━━━━\n[808080] R.I.P" },
    { category: "خطر", name: "سم", code: "[b][c][00ff00]☠ [ffffff]P O I S O N [00ff00] ☠\n[808080]▂▂▂▂▂▂▂▂" },
    { category: "خطر", name: "خطر", code: "[b][c][ff0000]⚠ [ffff00] D A N G E R [ff0000] ⚠\n[ffffff]── keep away ──" },
    { category: "خطر", name: "سكين", code: "[b][c][808080]──────────╮\n[ffffff]  B L A D E ╯\n[808080]──────────╯" },
    { category: "خطر", name: "ديناميت", code: "[b][c][ff0000]╔══╗\n[ffffff]║██║\n[ff0000]╚══╝\n[ffff00]─ T N T ─" },
    { category: "خطر", name: "ضربة قاضية", code: "[b][c][ff0000]▓▓░░▓▓\n[ffffff] K.O.\n[ff0000]▓▓░░▓▓" },
    { category: "خطر", name: "نظام خطأ", code: "[b][c][808080][ SYSTEM ERROR 404 ]" },
    { category: "خطر", name: "ماتريكس", code: "[b][c][00ff00]01001 10110\n[ffffff]M A T R I X\n[00ff00]10110 01001" },
    { category: "خطر", name: "قراصنة", code: "[b][c][ffffff]𝕻𝕴𝕽𝕬𝕿𝕰𝕾" },
    { category: "خطر", name: "جمجمة", code: "[b][c][ffffff]☠ [ff0000] K I L L E R [ffffff] ☠" },
    { category: "خطر", name: "سجن", code: "[b][c][808080]| | | | | |\n[ffffff] PRISONER\n[808080]| | | | | |" },

// === مجسمات وأشكال ===
    {category:"مجسمات",name:"سيارة",code:"[B][C][CCFF00]♡┏┯┓ ┏┛□┗━━━┓ ♡-ᴛʀᴜᴄᴋ ┗⊙━━━⊙━┛"},
    { category: "مجسمات", name: "طائرة", code: "[b][c][ffffff]──────────\n[00ffcc]  __|__\n[ffffff]────(•)────\n[00ffcc]  /   \\\n[ffffff]──────────" },
    { category: "مجسمات", name: "شاحنة", code: "[b][c][ffd700]████████████\n[ffffff]█[ff0000] TRUCK [ffffff]█\n[808080]◯──────────◯" },
    { category: "مجسمات", name: "صاروخ", code: "[b][c][ffffff] /\\\n /  \\\n[ff0000]████\n[ff8800]▲▲▲" },
    { category: "مجسمات", name: "قلعة", code: "[b][c][808080]▄█▄█▄█▄\n[ffffff]█[ffd700] ♛ [ffffff]█\n[808080]▀▀▀▀▀▀▀" },
    { category: "مجسمات", name: "سيارة سباق", code: "[b][c][ff0000]___________\n[ffffff]╱▐██████▌╲\n[808080]◯─────────◯" },
    { category: "مجسمات", name: "غواصة", code: "[b][c][0044ff]≈≈≈≈≈≈≈≈≈\n[ffffff]◄██████►\n[0044ff]≈≈≈≈≈≈≈≈≈" },
    { category: "مجسمات", name: "ساعة رملية", code: "[b][c][ffd700]╔════╗\n[ffffff]╚▄██▄╝\n[ffd700]╔▀██▀╗\n[ffffff]╚════╝" },
    { category: "مجسمات", name: "موجة صوت", code: "[b][c][00ff00]▁▂▃▄▅▆▇█▇▆▅▄▃▂▁" },
    { category: "مجسمات", name: "بيانو", code: "[b][c][ffffff]█▐█▐█ █▐█▐█\n[808080]▔▔▔▔▔▔▔▔▔" },
    { category: "مجسمات", name: "ثعبان", code: "[b][c][00ff00]~≈~≈~≈~≈~\n[ff0000] S N A K E\n[00ff00]~≈~≈~≈~≈~" },
    { category: "مجسمات", name: "خيمة", code: "[b][c][ff8800]  /\\\n /  \\\n/____\\" },
    { category: "مجسمات", name: "بصمة", code: "[b][c][ff0055]░▓██▓░\n[ffffff]▓██████▓\n[ff0055]░▓████▓░" },
    { category: "مجسمات", name: "نجمة الشمال", code: "[b][c][ffd700]  ★\n★   ★\n  ★" },
    { category: "مجسمات", name: "قمر وشمس", code: "[b][c][ffd700]─── ☀ ───\n[aaaaff]─── ☽ ───" },
    { category: "مجسمات", name: "شبكة", code: "[b][c][00ffcc]┼─┼─┼─┼\n├─┼─┼─┤\n[ffffff]┼─┼─┼─┼" },
        // === منصات ===
    { category: "منصات", name: "إنستا", code: "[b][c]╭─╮\n︱◯֯︱ɪɴꜱᴛᴀ حط اسمك [ff00ff]\n╰─╯", premium:true },
    { category: "منصات", name: "يوتيوب", code: "[b][c]╭─╮\n︱▶֯︱ʏᴏᴜᴛᴜʙᴇ حط اسمك [ff0000]\n╰─╯", premium:true },
    { category: "منصات", name: "تيك توك", code: "[B][C][00FFFF]╭─╮\n︱ꚠ︱тιктσк ┆ TikTok\n╰─╯", premium:true },
    { category: "منصات", name: "يوتيوب 2", code: "[B][00FFFF]╭──╮\n| ▶︎ | ʏ ᴛ ┊\n╰──" },
    { category: "منصات", name: "تويتر/X", code: "[b][c][1DA1F2]╭─╮\n[ffffff]︱✕֯︱ᴛᴡɪᴛᴛᴇʀ\n[1DA1F2]╰─╯" },
    { category: "منصات", name: "سناب شات", code: "[b][c][ffff00]╭─╮\n[ffffff]︱◉֯︱sɴᴀᴘᴄʜᴀᴛ\n[ffff00]╰─╯" },
    { category: "منصات", name: "تيليجرام", code: "[b][c][00aaff]╭─╮\n[ffffff]︱✈֯︱ᴛᴇʟᴇɢʀᴀᴍ\n[00aaff]╰─╯" },
    { category: "منصات", name: "واتساب", code: "[b][c][25D366]╭─╮\n[ffffff]︱☏֯︱ᴡʜᴀᴛsᴀᴘᴘ\n[25D366]╰─╯" },
    { category: "منصات", name: "فيسبوك", code: "[b][c][1877F2]╭─╮\n[ffffff]︱ғ֯︱ꜰᴀᴄᴇʙᴏᴏᴋ\n[1877F2]╰─╯" },
    { category: "منصات", name: "تويتش", code: "[b][c][9146FF]╭─╮\n[ffffff]︱▶֯︱ᴛᴡɪᴛᴄʜ\n[9146FF]╰─╯" },
    { category: "منصات", name: "ديسكورد", code: "[b][c][5865F2]╭─╮\n[ffffff]︱◎֯︱ᴅɪsᴄᴏʀᴅ\n[5865F2]╰─╯" },
    { category: "منصات", name: "شورتس", code: "[b][c][ff0000]╭─╮\n[ffffff]︱⚡֯︱sʜᴏʀᴛs\n[ff0000]╰─╯" },
    { category: "منصات", name: "هاتف 1", code: "[B][C]╭─╮\n︱☎︎︱ Where is the telephone ┆[FF00FF]?\n╰─╯" },
    { category: "منصات", name: "هاتف 2", code: "[B][00FFFF]╭─╮\n︱☎︎︱ There is no telephone ┆[CCFF00]!" },

    // === أعلام ===
    { category: "أعلام", name: "الجزائر", code: "[f0f2f5]██[ff0000]☾★[008751]██", premium:true  },
    { category: "أعلام", name: "المغرب", code: "[ff0000]█[00ff00]★[ff0000]█", premium:true },
    { category: "أعلام", name: "تونس", code: "[ff0000]█[ffffff]☪[ff0000]█", premium:true },
    { category: "أعلام", name: "فلسطين", code: "[000000]█[ffffff]█[008000]█\n[ff0000]▼", premium:true },
    { category: "أعلام", name: "السعودية", code: "[b][006c35]███[ffffff]⚔[006c35]███", premium:true },
    { category: "أعلام", name: "الإمارات", code: "[ff0000]█[008000]█[ffffff]█[000000]█", premium:true },
    { category: "أعلام", name: "مصر", code: "[b][ff0000]███[ffffff]█[ffd700]◆[ffffff]█[000000]███", premium:true },
    { category: "أعلام", name: "سوريا", code: "[b][ff0000]███[ffffff]★ ★[000000]███", premium:true },
    { category: "أعلام", name: "العراق", code: "[b][cc0001]███[ffffff]★ ★ ★[000000]███", premium:true },
    { category: "أعلام", name: "الكويت", code: "[b][007a3d]███[ffffff]█[ce1126]█[ffffff]█[007a3d]███", premium:true },
    { category: "أعلام", name: "قطر", code: "[b][8d1b3d]████[ffffff]███", premium:true },
    { category: "أعلام", name: "عُمان", code: "[b][db161b]███[ffffff]█[008000]███", premium:true },
    { category: "أعلام", name: "اليمن", code: "[b][ce1126]███[ffffff]███[000000]███", premium:true },
    { category: "أعلام", name: "السودان", code: "[b][ff0000]███[ffffff]███[000000]███[008000]▬▬▬", premium:true },
    { category: "أعلام", name: "ليبيا", code: "[b][000000]███[008000]█☽★█[000000]███", premium:true },
    { category: "أعلام", name: "موريتانيا", code: "[b][008000]███[ffd700]☽★[ff0000]▬▬▬", premium:true },
    { category: "أعلام", name: "الأردن", code: "[b][000000]███[ffffff]★[008000]███[ff0000]◀", premium:true },
    { category: "أعلام", name: "لبنان", code: "[b][ff0000]███[ffffff]█ ♣ █[ff0000]███", premium:true },
    { category: "أعلام", name: "برشلونة", code: "[b]F.C.B\n[A50044]██[004D98]██\n[004D98]██[A50044]██" },
    { category: "أعلام", name: "ريال", code: "[b]R.M.A\n[Ffffff]██[0A1A57]██\n[0A1A57]██[ffffff]██" },
    
    // === متنوعة ===
    { category: "متنوعة", name: "سيجار", code: "[b][6D7B8D]ᝰ[ffffff]▂▂[ffa000]▂" },
    { category: "متنوعة", name: "بينق", code: "[FF0000] ᯤ 9 9 9 +" },
    { category: "متنوعة", name: "نبض", code: "[ff0000]ﮩ٨ـﮩﮩ٨ـ♡ﮩ٨ـﮩﮩ٨ـ⁷" },
    { category: "متنوعة", name: "شحن بطارية", code: "[b][00ff00][ffffff]████████▒ 99%" },
    { category: "متنوعة", name: "مربعات شطرنج", code: "[b][c][ffffff]▀▄▀▄ [ff0000] CHESS [ffffff] ▀▄▀▄" },
    { category: "متنوعة", name: "اسم ملون", code: "[b][ff0000]S[ffff00]T[00ff00]E[00ffff]R[0000ff]B[ff00ff]E[ff0000]N" },
    { category: "متنوعة", name: "أوفلاين", code: "[b][c][808080]● Offline [ffffff] (عدت لاحقاً)" },
    { category: "متنوعة", name: "نت", code: "[B][C][FF0000]ᯤ 9 9 9 +[00FF00] What is the net" },
    { category: "متنوعة", name: "كود خاص", code: "[B][C][00FFFF](_̅(_̅(̅_̅_̅_̅_̅_̅_̅_̅_̅_̅()࿐" },
    
    // === Couple / حب ===
    { category: "حب", name: "قمر حبي", code: "[b][c][ff69b4]☾ [ffffff]MY MOON & STARS [ff69b4]☾\n[ffffff]━━━━━━━━━━━━\n[ffd700]FOREVER YOURS ♡", premium:true },
    { category: "حب", name: "حب فري فاير", code: "[b][c][ffd319]╱◥██████◣\n[ffffff]│∩│▤│▤│▤\n[ffffff]▓▓▓▓▓▓▓▓▓\n[ffffff]FF LOVE" , premium:true},
    { category: "حب", name: "تراك الحب", code: "[B][C][CCFF00]♡┏┯┓\n[ffffff]┏┛□┗━━━┓\n[ffffff]♡ [ffffff]LOVE TRUCK [ffffff]♡\n[ffffff]┗⊙━━━⊙━┛" , premium:true},
    { category: "حب", name: "قلب مضيء", code: "[b][c][ff69b4]♥ [ffffff]LOVE IS LIFE [ff69b4]♥\n[ffffff]────────────\n[ff0055]YOU AND ME", premium:true },
    { category: "حب", name: "أميرتي", code: "[b][c][ffd700]♛ [ffffff]MY PRINCESS [ffd700]♛\n[ffffff]────────────\n[ff69b4]QUEEN", premium:true },
    { category: "حب", name: "حكاية عشق", code: "[b][c][ff0055]∞ [ffffff]LOVE STORY [ff0055]∞\n[ffffff]────────────\n[ff69b4]FOREVER", premium:true },
    { category: "حب", name: "حب طفولي", code: "[b][c][ff69b4]✿ [ffffff]FIRST CRUSH [ff69b4]✿\n[ffffff]────────────\n[ffd700]ALWAYS" },
    { category: "حب", name: "ليلة قمر", code: "[b][c][aaaaff]☽ [ffffff]MOON NIGHT [aaaaff]☽\n[ffffff]────────────\n[ffffff]DREAMS" },
    { category: "حب", name: "غيمة وردية", code: "[b][c][ff69b4]☁ [ffffff]PINK CLOUD [ff69b4]☁\n[ffffff]────────────\n[ff0055]SWEET" },
    { category: "حب", name: "فراشة الحب", code: "[b][c][ff69b4]ʚ [ffffff]LOVE BUTTERFLY [ff69b4]ɞ\n[ffffff]────────────\n[00ffcc]FLY" },
    { category: "حب", name: "قلب ذهبي", code: "[b][c][ffd700]♥ [ffffff]GOLDEN HEART [ffd700]♥\n[ffffff]────────────\n[ff69b4]TRUE" },
    { category: "حب", name: "حب صامت", code: "[b][c][8888ff]● [ffffff]SILENT LOVE [8888ff]●\n[ffffff]────────────\n[ffffff]DEEP" },
    { category: "حب", name: "ابتسامة حلوة", code: "[b][c][ff69b4]☺ [ffffff]SWEET SMILE [ff69b4]☺\n[ffffff]────────────\n[ffd700]CUTE" },
    { category: "حب", name: "نبض", code: "[ff0000]ﮩ٨ـﮩﮩ٨ـ♡ﮩ٨ـﮩﮩ٨ـ⁷" },
    { category: "حب", name: "زوجان", code: "[b][c][ff69b4]Together Forever\n[ff0055]♡ [ffffff]YOU + ME [ff0055]♡\n[ff69b4]────────────" },
    { category: "حب", name: "قلبان", code: "[b][c][ff0055]♥[ffffff] You [ff69b4]&[ffffff] Me [ff0055]♥\n[ff69b4]━━━━━━━━━━━" },
    { category: "حب", name: "رومانسي", code: "[b][c][ff69b4]✿ [ff0055]LOVE[ff69b4] ✿\n[ffffff]────────────" },
    { category: "حب", name: "إلى الأبد", code: "[b][c][ffffff]Forever &[ff0055] Always ♡\n[ff69b4]────────────" },
    { category: "حب", name: "نجمة حب", code: "[b][c][ffd700]★ [ff69b4]My Love[ffd700] ★\n[ffffff]──────────" },
    { category: "حب", name: "وردة", code: "[b][c][ff0055]✿ Rose ✿\n[ff69b4]────────────" },
    { category: "حب", name: "غروب", code: "[b][c][ff8c00]Sunset Vibes\n[ff69b4]♡ ♡ ♡" },
    { category: "حب", name: "سر", code: "[b][i][c][ff69b4]Secret Love\n[ffffff]────────────" },
    { category: "حب", name: "كراش", code: "[b][c][ff69b4]Thinking of you\n[ff0055]♡ Always ♡" },
    { category: "حب", name: "اعتراف", code: "[b][c][ffffff]My Heart[ff0055] is Yours\n[ff69b4]♡ ♡ ♡" },
    { category: "حب", name: "فراشات", code: "[b][c][ff69b4]Butterflies\n[ffffff]Every time I see you\n[ff0055]♡" },
    { category: "حب", name: "نظرة", code: "[b][c][ff69b4]One Look\n[ffffff]That's all it took\n[ff0055]♡" },
    { category: "حب", name: "مغازلة", code: "[b][c][ff69b4]Flirt Mode ON\n[ff0055]♡ ♡ ♡\n[ffffff]────────────" },
    { category: "حب", name: "جميلة", code: "[b][c][ffd700]Pretty & Wild\n[ff69b4]♡ ♡ ♡" },
    { category: "حب", name: "ابتسامة", code: "[b][c][ffffff]Your Smile[ff69b4] ♡\n[ff0055]Kills Me Daily" },
    { category: "حب", name: "قلب مسروق", code: "[b][c][ff0055]You Stole My Heart\n[ff69b4]And I'm OK With It\n[ffffff]♡" },
    { category: "حب", name: "اشتياق", code: "[b][c][8888ff]Missing You\n[ffffff]Every single day\n[ff69b4]♡" },
    { category: "حب", name: "بعيد", code: "[b][c][8888ff]Far Away\n[ffffff]But Always Near\n[ff69b4]♡" },
    { category: "حب", name: "حنين", code: "[b][i][c][8888ff]I Miss the way\n[ffffff]You smile\n[ff69b4]♡" },
    { category: "حب", name: "ذكرى", code: "[b][c][8888ff]Still Thinking\n[ffffff]Of our memories\n[ff69b4]♡" },
    { category: "حب", name: "حزين", code: "[b][i][c][8888ff]Broken But Alive\n[808080]....." },
    { category: "حب", name: "صامت", code: "[b][i][c][808080]Silent Pain\n[ffffff]No one understands" },
    { category: "حب", name: "وحيد", code: "[b][c][8888ff]Alone in a crowd\n[808080]────────────" },
    { category: "حب", name: "عميق", code: "[b][i][c][ffffff]Deep Emotions\n[8888ff]Can't explain\n[ff69b4]♡" },
    { category: "حب", name: "قلب لوحده", code: "[b][c][ff0055]╔══════╗\n[ff69b4] ♡ LOVE ♡\n[ff0055]╚══════╝" },
    { category: "حب", name: "أميرة", code: "[b][c][ffd700]★ Princess ★\n[ff69b4]────────────" },
    { category: "حب", name: "فارس", code: "[b][c][ffd700]★ Knight ★\n[ff69b4]────────────" },
    { category: "حب", name: "حب أبدي", code: "[b][c][ff0055]∞ [ff69b4]Endless Love [ff0055]∞\n[ffffff]────────────" },
    { category: "حب", name: "قصيدة", code: "[b][i][c][ff69b4]You are my poem\n[ff0055]My reason to smile\n[ffffff]♡" },
    { category: "حب", name: "نجوم", code: "[b][c][ffd700]★ [ff69b4]Stargazing[ffd700] ★\n[ffffff]Thinking of you" },
    
    // === Attitude & Swagger ===
    { category: "موقف", name: "عقلية ألفا", code: "[b][c][ff0000]■ [ffffff]ALPHA MINDSET [ff0000]■\n[ffffff]────────────\n[ff7b00]LEADER", premium:true },
    { category: "موقف", name: "ثقة عمياء", code: "[b][c][ffd700]★ [ffffff]BLIND CONFIDENCE [ffd700]★\n[ffffff]────────────\n[ffffff]BOSS", premium:true },
    { category: "موقف", name: "ملك السافاج", code: "[b][c][ff0000]☠ [ffffff]SAVAGE KING [ff0000]☠\n[ffffff]────────────\n[808080]FEARLESS", premium:true },
    { category: "موقف", name: "قيصر الزمن", code: "[b][c][ffd700]♔ [ffffff]TIME CAESAR [ffd700]♔\n[ffffff]────────────\n[ffffff]RULER", premium:true },
    { category: "موقف", name: "أسد المعركة", code: "[b][c][ff7b00]◉ [ffffff]BATTLE LION [ff7b00]◉\n[ffffff]────────────\n[ff0000]ROAR", premium:true },
    { category: "موقف", name: "الأسطورة الحرة", code: "[b][c][00ffcc]∞ [ffffff]FREE LEGEND [00ffcc]∞\n[ffffff]────────────\n[ffd700]ICON", premium:true },
    { category: "موقف", name: "غازي القمة", code: "[b][c][ff0000] [ffffff]TOP INVADER [ff0000]\n[ffffff]────────────\n[ffffff]RUSH" },
    { category: "موقف", name: "نمر الهيمنة", code: "[b][c][ff7b00]▣ [ffffff]DOMINANT TIGER [ff7b00]▣\n[ffffff]────────────\n[ff0000]POWER" },
    { category: "موقف", name: "ذئب السيرفر", code: "[b][c][808080]◈ [ffffff]SERVER WOLF [808080]◈\n[ffffff]────────────\n[ffffff]ALPHA" },
    { category: "موقف", name: "فايكنج", code: "[b][c][00ffff]⚔ [ffffff]VIKING SPIRIT [00ffff]⚔\n[ffffff]────────────\n[808080]WARRIOR" },
    { category: "موقف", name: "ألفا", code: "[b][c][ff0000]ALPHA[ffffff] MODE\n[ff7b00]━━━━━━━━━━━━" },
    { category: "موقف", name: "سافاج", code: "[b][c][ff0000]SAVAGE[ffffff] & PROUD\n[808080]────────────" },
    { category: "موقف", name: "سيجما", code: "[b][c][ffffff]SIGMA[ff7b00] MINDSET\n[ffffff]━━━━━━━━━━━━" },
    { category: "موقف", name: "بوس", code: "[b][c][ffd700]BORN[ffffff] TO BE\n[ff7b00]THE BOSS\n[ffd700]━━━━━━━━━━" },
    { category: "موقف", name: "لا أهتم", code: "[b][i][c][808080]I Don't Care\n[ffffff]What You Think\n[808080]────────────" },
    { category: "موقف", name: "مختلف", code: "[b][c][00ffcc]DIFFERENT[ffffff] BY\n[00ffcc]CHOICE\n[ffffff]━━━━━━━━━━" },
    { category: "موقف", name: "كسبان", code: "[b][c][ffd700]WINNERS[ffffff] FOCUS\n[ffd700]LOSERS[ffffff] GOSSIP" },
    { category: "موقف", name: "وحش", code: "[b][c][ff0000]BEAST[ffffff] MODE\n[ff0000]━◤[ffffff] ACTIVATED [ff0000]◥━" },
    { category: "موقف", name: "كبرياء", code: "[b][c][ff7b00]TOO[ffffff] REAL FOR\n[ff7b00]FAKE[ffffff] PEOPLE" },
    { category: "موقف", name: "صامد", code: "[b][c][ffffff]THEY TRIED\n[ff0000]I SURVIVED\n[ffffff]━━━━━━━━━━" },
    { category: "موقف", name: "راقي", code: "[b][c][ffd700]CLASS[ffffff] ABOVE\n[ffd700]THE[ffffff] REST\n[808080]────────────" },
    { category: "موقف", name: "مجنون", code: "[b][c][ff00ff]CRAZY[ffffff] BUT\n[ff00ff]LEGENDARY\n[ffffff]────────────" },

    // === Gaming Pro ===
    { category: "ألعاب", name: "إيليت", code: "[b][c][7F00FF]◥█▓▓█◤\n[ffffff]FF ELITE\n[7F00FF]◥█▓▓█◤", premium:true },
    { category: "ألعاب", name: "بوياه", code: "[b][c][FF0000]●\n[ffffff]BOOYAH\n[ffffff]█\\▄█" },
    { category: "ألعاب", name: "زعيم السيرفر", code: "[b][c][ff0000]╔═════════╗\n[ffffff]SERVER OWNER\n[ff0000]╚═════════╝" },
    { category: "ألعاب", name: "سولو كينج", code: "[b][c][ffd700]♛ [ffffff]SOLO KING [ffd700]♛\n[ffffff]────────────\n[00ffcc]NO FEAR" },
    { category: "ألعاب", name: "جود مود", code: "[b][c][00ff00]● [ffffff]GOD MODE ACTIVE [00ff00]●\n[ffffff]────────────\n[ffd700]UNSTOPPABLE" },
    { category: "ألعاب", name: "صائد الرؤوس", code: "[b][c][ff0000]︻デ═一 [ffffff]HEADSHOT KING\n[ffffff]────────────\n[ffd700]ONE TAP" },
    { category: "ألعاب", name: "بطل الموسم", code: "[b][c][ff2d55]★ [ffffff]SEASON HERO [ff2d55]★\n[ffffff]────────────\n[00ffff]TOP 1 REGION" },
    { category: "ألعاب", name: "وحش الفري فاير", code: "[b][c][ff0000]☠ [ffffff]FF BEAST [ff0000]☠\n[ffffff]────────────\n[ffd700]KILLS MACHINE" },
    { category: "ألعاب", name: "بطل اللوبي", code: "[b][c][00ffcc]◆ [ffffff]LOBBY HERO [00ffcc]◆\n[ffffff]────────────\n[ffffff]ALL GUNS MASTER" },
    { category: "ألعاب", name: "القادم القوي", code: "[b][c][ff7b00]⚡ [ffffff]NEXT LEVEL [ff7b00]⚡\n[ffffff]────────────\n[00ffcc]BEST RUNNER" },
    { category: "ألعاب", name: "فخر العرب", code: "[b][c][ffd700]◉ [ffffff]ARAB PRIDE [ffd700]◉\n[ffffff]────────────\n[008000]RESPECT ALL" },
    { category: "ألعاب", name: "قوة خارقة", code: "[b][c][ff00ff]▣ [ffffff]SUPER POWER [ff00ff]▣\n[ffffff]────────────\n[ffffff]NO ONE CAN STOP ME" },
    { category: "ألعاب", name: "لوبي", code: "[b][c][ff0000]╔═[ [ffffff]LOBBY OWNER [ff0000]]═╗\n[ffffff]   ALL MINE\n[ff0000]╚═══════════════╝" },
    { category: "ألعاب", name: "عدو يهرب", code: "[b][c][ff9900]Enemies panic\n[ff0000]■デ━━━━[ffffff] when I rush\n[ff9900]━━━━━━━━━━━━" },
    { category: "ألعاب", name: "فاينال بوس", code: "[b][c][ff0000]■デ━━━━\n[ffffff]| [00ff00]FINAL BOSS [ffffff]|\n[ff0000]━━━━━━━━━━━━" },
    { category: "ألعاب", name: "مشكلة", code: "[b][c][ff9900]Not a player\n[ff0000]I'm a PROBLEM\n[ff9900]■デ━━━━━━━━━" },
    { category: "ألعاب", name: "سولو ليجند", code: "[b][c][ff0000]■デ━━━━\n[ff9900]| SOLO LEGEND |\n[ff0000]| NO TEAM NEEDED |" },
    { category: "ألعاب", name: "تحكم", code: "[b][c][ff9900]Zone control\n[ff0000]Aim control\n[ff9900]Game control\n[ff0000]■デ━━━━━━━━━" },
    { category: "ألعاب", name: "كلتش", code: "[b][c][ff0000]■デ━━━━\n[ffffff]| [00ff00]CLUTCH BEAST [ffffff]|\n[ff0000]━━━━━━━━━━━━" },
    { category: "ألعاب", name: "ريسبون", code: "[b][c][ff9900]Fight me =\n[ff0000]respawn lobby\n[ff9900]■デ━━━━━━━━━" },
    { category: "ألعاب", name: "هيدشوت", code: "[b][c][ff0000]╔══[ [ffd700]HEADSHOT [ff0000]]══╗\n[ffffff] One Shot One Kill\n[ff0000]╚══════════════╝" },
    { category: "ألعاب", name: "نو لوس", code: "[b][c][00ff00]NO[ff0000] LOSS[ffffff] ONLY\n[00ff00]LESSONS\n[ffffff]━━━━━━━━━━━━" },
    
    // === تحفيز ===
    { category: "تحفيز", name: "النجاح", code: "[B][00FFFF]╬═╬\n[ffffff]╬═╬ \n[ffffff]▌[ffffff]SUCCESS [ffffff]▌\n[00FFFF]╬═╬", premium:true },
    { category: "تحفيز", name: "العمل بصمت", code: "[b][c][ffffff]Work Hard in [00d9ff]Silence\n[ffffff]Let Success be your [00d9ff]Noise\n[00d9ff]────────────", premium:true },
    { category: "تحفيز", name: "لا استسلام", code: "[b][c][ff2d55]NEVER [ffffff]GIVE UP\n[ffffff]Great things take [ff2d55]Time\n[ff2d55]★ ★ ★ ★ ★", premium:true },
    { category: "تحفيز", name: "كن بطلاً", code: "[b][c][ffd700]Don't wait for [ffffff]Opportunity\n[ffd700]CREATE IT\n[ffffff]━━━━━━━━━━━━", premium:true },
    { category: "تحفيز", name: "الأفضل قادم", code: "[b][c][00e676]The Best is [ffffff]Yet To Come\n[00e676]Keep Moving [ffffff]Forward\n[00e676]● ──── ● ──── ●", premium:true },
    { category: "تحفيز", name: "تحدي الذات", code: "[b][c][7b5ef8]Be your own [ffffff]Hero\n[7b5ef8]Beat your own [ffffff]Records\n[7b5ef8]⚔️ ──────── ⚔️", premium:true },
    { category: "تحفيز", name: "قوة الإرادة", code: "[b][c][ff6b2b]Pain is [ffffff]Temporary\n[ff6b2b]Pride is [ffffff]Forever\n[ff6b2b]━━━━━━━━━━━━", premium:true },
    { category: "تحفيز", name: "عقلية الفوز", code: "[b][c][ffffff]Winners [00ffcc]Never Quit\n[ffffff]Quitters [ff0000]Never Win\n[00ffcc]────────────" },
    { category: "تحفيز", name: "انضباط", code: "[b][c][ffffff]Discipline > [ff2d55]Motivation\n[ffffff]Focus on the [ff2d55]Goal\n[ff2d55]99% Loading..." },
    { category: "تحفيز", name: "حلم كبير", code: "[b][c][00d9ff]Dream [ffffff]BIG\n[00d9ff]Stay [ffffff]HUMBLE\n[00d9ff]✨ ──────── ✨" },
    { category: "تحفيز", name: "صناعة المجد", code: "[b][c][ffd700]Legendary [ffffff]Status\n[ffd700]In the [ffffff]Making\n[ffd700]♛ ──────── ♛" },

    // === Funny & Chill ===
    { category: "مضحك", name: "الهند وباكستان", code: "[B][00FFFF]●\n[ffffff]INDIA VS PAKISTAN\n[ffffff]█\\ ▄█﹅▃█▀█●" , premium:true},
    { category: "مضحك", name: "مواجهة النيون", code: "[b][c][00ffff]█▀█ [ffffff]YOU [ff0000]VS [ffffff]ME [ff0000]█▀█\n[00ffff]●───────────●\n[ffffff]STATUS: [00ff00]GOD MODE" , premium:true},
    { category: "مضحك", name: "fake", code: "[B][00FFFF]  RAI VS JAY\n ●█▄█﹅[FFFFFF]▃█▀█● ", premium:true},
    { category: "مضحك", name: "لاقيت", code: "[b][c][ffd700]Finally Found\n[00ffcc]The WiFi Password\n[ffffff]Life is Good" },
    { category: "مضحك", name: "نوم", code: "[b][i][c][8888ff]Currently Offline\n[ffffff]Gone to Sleep\n[8888ff]zzzZZZ..." },
    { category: "مضحك", name: "배고파", code: "[b][c][ff7b00]Hungry 24/7\n[ffffff]Send Food Pls\n[ff7b00]━━━━━━━━━━" },
    { category: "مضحك", name: "فقير", code: "[b][c][808080]My Bank Account\n[ff0000]Be Like: Error\n[808080]━━━━━━━━━━" },
    { category: "مضحك", name: "محتاج", code: "[b][c][ffd700]Need Coffee\n[ff7b00]Before Talking\n[ffd700]━━━━━━━━━━" },
    { category: "مضحك", name: "بدون عقل", code: "[b][i][c][ff00ff]Warning:\n[ffffff]Brain Not Found\n[ff00ff]Please Restart" },
    { category: "مضحك", name: "جيمر حياة", code: "[b][c][00ff00]Sleep:[ff0000] Error\n[ffd700]Eat:[ff0000] Skip\n[00ffcc]Game:[00ff00] Online" },
    { category: "مضحك", name: "تحميل الحظ", code: "[b][c][ffffff]Loading Luck...\n[ff0000]Error: [ffffff]404\n[ff0000]Luck Not Found" },
    { category: "مضحك", name: "بطارية منخفضة", code: "[b][c][ff6b2b]Brain Battery: [ff0000]5%\n[ffffff]Please insert coffee\n[ff6b2b]━━━━━━━━━━━━" },
    
    // === Aesthetic ===
    { category: "جمالي", name: "سماء أرجوانية", code: "[b][c][8888ff]☁ [ffffff]PURPLE SKY [8888ff]☁\n[ffffff]────────────\n[aaaaff]DREAMS", premium:true },
    { category: "جمالي", name: "غابة سحرية", code: "[b][c][00ffcc]✿ [ffffff]MAGIC FOREST [00ffcc]✿\n[ffffff]────────────\n[008000]PEACE", premium:true },
    { category: "جمالي", name: "نسمة بحر", code: "[b][c][00ffff]~ [ffffff]SEA BREEZE [00ffff]~\n[ffffff]────────────\n[ffffff]CALM", premium:true },
    { category: "جمالي", name: "فجر جديد", code: "[b][c][ff8c00]☀ [ffffff]NEW DAWN [ff8c00]☀\n[ffffff]────────────\n[ffd700]HOPE", premium:true },
    { category: "جمالي", name: "فضاء عميق", code: "[b][c][8888ff]• [ffffff]DEEP SPACE [8888ff]•\n[ffffff]────────────\n[aaaaff]STARS", premium:true },
    { category: "جمالي", name: "صمت الليل", code: "[b][c][808080]☽ [ffffff]NIGHT SILENCE [808080]☽\n[ffffff]────────────\n[ffffff]MOON", premium:true },
    { category: "جمالي", name: "وردة زرقاء", code: "[b][c][00ffff]✿ [ffffff]BLUE ROSE [00ffff]✿\n[ffffff]────────────\n[ffffff]RARE" },
    { category: "جمالي", name: "رياح باردة", code: "[b][c][00ffcc]~ [ffffff]COLD WIND [00ffcc]~\n[ffffff]────────────\n[ffffff]FRESH" },
    { category: "جمالي", name: "ضوء قمري", code: "[b][c][aaaaff]☾ [ffffff]MOON LIGHT [aaaaff]☾\n[ffffff]────────────\n[ffd700]GLOW" },
    { category: "جمالي", name: "محيط هادئ", code: "[b][c][0044ff]~ [ffffff]QUIET OCEAN [0044ff]~\n[ffffff]────────────\n[00ffff]DEEP" },
    { category: "جمالي", name: "فضاء", code: "[b][c][ffffff]lost in [8888ff]space\n[ffffff]finding [aaaaff]stars\n[8888ff]✧ ─── ☾ ─── ✧" },
    { category: "جمالي", name: "هدوء", code: "[b][c][00ffcc]Stay [ffffff]Simple\n[00ffcc]Stay [ffffff]Real\n[00ffcc]────────────" },
    { category: "جمالي", name: "سيلين", code: "[b][c][8888ff]soft[ffffff] like clouds\n[aaaaff]deep[ffffff] like ocean\n[8888ff]────────────" },
    { category: "جمالي", name: "قمر", code: "[b][c][aaaaff]chasing [ffd700]moonlight\n[ffffff]& [8888ff]midnight dreams\n[aaaaff]────────────" },
    { category: "جمالي", name: "بارد", code: "[b][i][c][00ffcc]cold[ffffff] outside\n[8888ff]warm[ffffff] inside\n[aaaaff]────────────" },
    { category: "جمالي", name: "غيوم", code: "[b][c][aaaaff]head in [ffffff]clouds\n[8888ff]heart on [ffffff]fire\n[aaaaff]────────────" },
    { category: "جمالي", name: "هادئ", code: "[b][i][c][8888ff]quiet[ffffff] soul\n[aaaaff]loud[ffffff] dreams\n[8888ff]────────────" },
    { category: "جمالي", name: "ليلي", code: "[b][c][ffffff]born at [8888ff]midnight\n[aaaaff]living in [ffffff]neon\n[8888ff]────────────" },
    { category: "جمالي", name: "مطر", code: "[b][i][c][8888ff]petrichor[ffffff] &\n[aaaaff]overthinking\n[8888ff]────────────" },
    { category: "جمالي", name: "فني", code: "[b][c][ff69b4]art[ffffff] is my\n[aaaaff]first[ffffff] language\n[ff69b4]────────────" },
];
